version: '3.4'

services:
  userservice:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"

    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MicroServiceBTHDb;User=sa;Password=Arleliot12!;TrustServerCertificate=True;MultipleActiveResultSets=true
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Arleliot12!"

volumes:
  mssql_data:

